### ISSUE TITLE
project:watch task doesn't copy files, when changed

### ISSUE THREAD

**Issue by lumnn** [beyondit/opencart-project-template#2]
When running `bin/robo project:watch`, it doesn't copy modified files to www.
Checked on Windows and Linux.

Changing lines 111 and 113 of RoboFile.php from `$this->taskWatch()` to `$this->projectDeploy()` fixes the issue.

**Comment by stefanhuber** [comment]
good point! Thx, also the composer dependency of lurker was missing!
